# Generated by Django 5.1.2 on 2025-06-10 20:41

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zettelkasten", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zettel",
            name="content",
            field=markdownx.models.MarkdownxField(),
        ),
    ]
