# Generated by Django 5.1.2 on 2025-06-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zettelkasten", "0005_alter_zettel_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zettel",
            name="title",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
