# Generated by Django 5.1.2 on 2025-06-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zettelkasten", "0006_alter_zettel_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zettel",
            name="title",
            field=models.CharField(max_length=250),
        ),
    ]
