# Generated by Django 5.1.2 on 2025-07-02 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zettelkasten", "0007_alter_zettel_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="zettel",
            name="slug",
            field=models.SlugField(max_length=250),
        ),
        migrations.AlterUniqueTogether(
            name="zettel",
            unique_together={("author", "title")},
        ),
    ]
