# Generated by Django 5.1.2 on 2025-07-02 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zettelkasten", "0008_alter_zettel_slug_alter_zettel_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="zettel",
            name="tags",
        ),
    ]
