# Generated by Django 5.1.2 on 2025-07-23 19:18

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("zettelkasten", "0009_remove_zettel_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="zettel",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="zettelkasten.folder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="zettel",
            unique_together={("author", "title")},
        ),
        migrations.AddField(
            model_name="zettel",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="zettels",
                to="zettelkasten.folder",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="zettel",
            unique_together={("author", "folder", "title"), ("author", "title")},
        ),
        migrations.AddIndex(
            model_name="folder",
            index=models.Index(
                fields=["-created"], name="zettelkaste_created_6a6a07_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="folder",
            unique_together={("author", "name", "parent")},
        ),
    ]
