# Generated by Django 5.1.2 on 2025-07-30 11:37

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        (
            "zettelkasten",
            "0010_zettel_tags_folder_alter_zettel_unique_together_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="zettel",
            unique_together={("author", "folder", "title")},
        ),
        migrations.AddField(
            model_name="folder",
            name="is_root",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="zettel",
            name="folder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="zettels",
                to="zettelkasten.folder",
            ),
        ),
        migrations.AlterField(
            model_name="zettel",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
