# Generated by Django 5.1.2 on 2025-07-30 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zettelkasten", "0011_alter_zettel_unique_together_folder_is_root_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="zettel",
            name="slug",
        ),
    ]
