# Generated by Django 5.1.2 on 2025-08-04 19:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zettelkasten", "0013_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="file",
            old_name="title",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="zettel",
            old_name="title",
            new_name="name",
        ),
        migrations.AlterUniqueTogether(
            name="file",
            unique_together={("author", "folder", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="zettel",
            unique_together={("author", "folder", "name")},
        ),
    ]
