# Generated by Django 5.1.2 on 2025-08-04 23:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("zettelkasten", "0014_rename_title_to_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="file",
            options={"ordering": ["-name"]},
        ),
        migrations.AlterModelOptions(
            name="folder",
            options={"ordering": ["-name"]},
        ),
        migrations.AlterModelOptions(
            name="zettel",
            options={"ordering": ["-name"]},
        ),
        migrations.RemoveIndex(
            model_name="file",
            name="zettelkaste_created_5faa33_idx",
        ),
        migrations.RemoveIndex(
            model_name="folder",
            name="zettelkaste_created_6a6a07_idx",
        ),
        migrations.RemoveIndex(
            model_name="zettel",
            name="zettelkaste_created_acf3df_idx",
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(fields=["-name"], name="zettelkaste_name_d5c420_idx"),
        ),
        migrations.AddIndex(
            model_name="folder",
            index=models.Index(fields=["-name"], name="zettelkaste_name_dcab17_idx"),
        ),
        migrations.AddIndex(
            model_name="zettel",
            index=models.Index(fields=["-name"], name="zettelkaste_name_030e0a_idx"),
        ),
    ]
